In [64]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import joblib


In [65]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,f1_score


# Load the dataset from the CSV file
file_path = "manufacturing_data.csv"  # Replace with the path to your dataset
data = pd.read_csv(file_path)

# Preprocessing

# 1. Convert "Downtime" column to binary labels
data["Downtime_Flag"] = data["Downtime"].apply(lambda x: 1 if x == "Machine_Failure" else 0)
data = data.drop("Downtime", axis=1)

# 2. Convert "Date" column to datetime and extract useful features
data["Date"] = pd.to_datetime(data["Date"], format="%d-%m-%Y")
data["Year"] = data["Date"].dt.year
data["Month"] = data["Date"].dt.month
data = data.drop("Date", axis=1)

# 3. Handle categorical columns with one-hot encoding
data = pd.get_dummies(data, columns=["Machine_ID", "Assembly_Line_No"], drop_first=True)

# 4. Handle missing values by filling with the mean (or drop rows if preferred)
data = data.fillna(data.mean())

# Split features and target
X = data.drop("Downtime_Flag", axis=1)
y = data["Downtime_Flag"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


In [66]:

# Train a Logistic Regression Model

# Create a pipeline with scaling and logistic regression
clf = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=500, random_state=42, class_weight='balanced')
)

# Train the model
clf.fit(X_train, y_train)

# Evaluate the model
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))




Accuracy: 1.0
Confusion Matrix:
 [[245   0]
 [  0 251]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       245
           1       1.00      1.00      1.00       251

    accuracy                           1.00       496
   macro avg       1.00      1.00      1.00       496
weighted avg       1.00      1.00      1.00       496



In [67]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the dataset from the CSV file
file_path = "manufacturing_data.csv"  # Replace with the path to your dataset
data = pd.read_csv(file_path)

# Preprocessing

# 1. Convert "Downtime" column to binary labels
data["Downtime_Flag"] = data["Downtime"].apply(lambda x: 1 if x == "Machine_Failure" else 0)
data = data.drop("Downtime", axis=1)

# 2. Convert "Date" column to datetime and extract useful features
data["Date"] = pd.to_datetime(data["Date"], format="%d-%m-%Y")
data["Year"] = data["Date"].dt.year
data["Month"] = data["Date"].dt.month
data = data.drop("Date", axis=1)

# 3. Handle categorical columns with one-hot encoding
data = pd.get_dummies(data, columns=["Machine_ID", "Assembly_Line_No"], drop_first=True)

# 4. Handle missing values by filling with the mean (or drop rows if preferred)
data = data.fillna(data.mean())

# Split features and target
X = data.drop("Downtime_Flag", axis=1)
y = data["Downtime_Flag"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)



# Train a Random Forest Classifier
clf = RandomForestClassifier(
    n_estimators=100,  # Number of trees
    max_depth=None,    # No limit on tree depth
    random_state=42,
    class_weight="balanced"  # Handle class imbalance
)

# Fit the model
clf.fit(X_train, y_train)

# Evaluate the model
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 1.0
Confusion Matrix:
 [[245   0]
 [  0 251]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       245
           1       1.00      1.00      1.00       251

    accuracy                           1.00       496
   macro avg       1.00      1.00      1.00       496
weighted avg       1.00      1.00      1.00       496



In [68]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,f1_score


# Load the dataset from the CSV file
file_path = "manufacturing_data.csv"  # Replace with the path to your dataset
data = pd.read_csv(file_path)

# Preprocessing

# 1. Convert "Downtime" column to binary labels
data["Downtime_Flag"] = data["Downtime"].apply(lambda x: 1 if x == "Machine_Failure" else 0)
data = data.drop("Downtime", axis=1)

# 2. Convert "Date" column to datetime and extract useful features
data["Date"] = pd.to_datetime(data["Date"], format="%d-%m-%Y")
data["Year"] = data["Date"].dt.year
data["Month"] = data["Date"].dt.month
data = data.drop("Date", axis=1)

# 3. Handle categorical columns with one-hot encoding
data = pd.get_dummies(data, columns=["Machine_ID", "Assembly_Line_No"], drop_first=True)

# 4. Handle missing values by filling with the mean (or drop rows if preferred)
data = data.fillna(data.mean())

# Split features and target
X = data.drop("Downtime_Flag", axis=1)
y = data["Downtime_Flag"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)



# Train a Decision Tree Classifier
clf_dt = DecisionTreeClassifier(
    max_depth=None,  # No limit on tree depth
    random_state=42,
    class_weight="balanced"  # Handle class imbalance
)

# Fit the model
clf_dt.fit(X_train, y_train)

# Evaluate the model
y_pred_dt = clf_dt.predict(X_test)
print("Decision Tree Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("Classification Report:\n", classification_report(y_test, y_pred_dt))
print("F1-Scpre:\n", f1_score(y_test, y_pred_dt))


Decision Tree Classifier
Accuracy: 1.0
Confusion Matrix:
 [[245   0]
 [  0 251]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       245
           1       1.00      1.00      1.00       251

    accuracy                           1.00       496
   macro avg       1.00      1.00      1.00       496
weighted avg       1.00      1.00      1.00       496

F1-Scpre:
 1.0


In [69]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,f1_score


# Load the dataset from the CSV file
file_path = "manufacturing_data.csv"  # Replace with the path to your dataset
data = pd.read_csv(file_path)

# Preprocessing

# 1. Convert "Downtime" column to binary labels
data["Downtime_Flag"] = data["Downtime"].apply(lambda x: 1 if x == "Machine_Failure" else 0)
data = data.drop("Downtime", axis=1)

# 2. Convert "Date" column to datetime and extract useful features
data["Date"] = pd.to_datetime(data["Date"], format="%d-%m-%Y")
data["Year"] = data["Date"].dt.year
data["Month"] = data["Date"].dt.month
data = data.drop("Date", axis=1)

# 3. Handle categorical columns with one-hot encoding
data = pd.get_dummies(data, columns=["Machine_ID", "Assembly_Line_No"], drop_first=True)

# 4. Handle missing values by filling with the mean (or drop rows if preferred)
data = data.fillna(data.mean())

# Split features and target
X = data.drop("Downtime_Flag", axis=1)
y = data["Downtime_Flag"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


# Train a K-Nearest Neighbors Classifier
clf_knn = KNeighborsClassifier(
    n_neighbors=5,  # Default: 5 neighbors
    weights="uniform"  # Uniform weighting of neighbors
)

# Fit the model
clf_knn.fit(X_train, y_train)

# Evaluate the model
y_pred_knn = clf_knn.predict(X_test)
print("K-Nearest Neighbors Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("Classification Report:\n", classification_report(y_test, y_pred_knn))
print("F1-Scpre:\n", f1_score(y_test, y_pred_dt))


K-Nearest Neighbors Classifier
Accuracy: 0.9838709677419355
Confusion Matrix:
 [[242   3]
 [  5 246]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.99      0.98       245
           1       0.99      0.98      0.98       251

    accuracy                           0.98       496
   macro avg       0.98      0.98      0.98       496
weighted avg       0.98      0.98      0.98       496

F1-Scpre:
 1.0


In [70]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the dataset
file_path = "train.csv"  # Replace with the path to your dataset
data = pd.read_csv(file_path)

# Preprocessing

# 1. Convert "Type" (categorical) into one-hot encoded columns
data = pd.get_dummies(data, columns=["Type"], drop_first=True)

# 2. Define features (X) and target (y)
X = data.drop(["id", "Product ID", "Machine failure"], axis=1)  # Drop non-predictive columns
y = data["Machine failure"]  # Target column

# 3. Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Logistic Regression Pipeline
clf = make_pipeline(
    StandardScaler(),  # Scale features for better model performance
    LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')  # Handle class imbalance
)

# Train the model
clf.fit(X_train, y_train)

# Evaluate the model
y_pred = clf.predict(X_test)

print("Logistic Regression Results:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the dataset
file_path = "train.csv"  # Replace with the path to your dataset
data = pd.read_csv(file_path)

# Preprocessing

# 1. Convert "Type" (categorical) into one-hot encoded columns
data = pd.get_dummies(data, columns=["Type"], drop_first=True)

# 2. Define features (X) and target (y)
X = data.drop(["id", "Product ID", "Machine failure"], axis=1)  # Drop non-predictive columns
y = data["Machine failure"]  # Target column

# 3. Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Random Forest Classifier
clf_rf = RandomForestClassifier(
    n_estimators=100,        # Number of trees
    max_depth=None,          # No limit on tree depth
    random_state=42,         # Ensure reproducibility
    class_weight="balanced"  # Handle class imbalance
)

# Train the model
clf_rf.fit(X_train, y_train)

# Evaluate the model
y_pred_rf = clf_rf.predict(X_test)

print("Random Forest Classifier Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))


Random Forest Classifier Results:
Accuracy: 0.9960785750934545
Confusion Matrix:
 [[26842    14]
 [   93   337]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     26856
           1       0.96      0.78      0.86       430

    accuracy                           1.00     27286
   macro avg       0.98      0.89      0.93     27286
weighted avg       1.00      1.00      1.00     27286



In [ ]:
import pandas as pd
import numpy as np

# Load Dataset 2
file_path = "train.csv"  # Replace with your Dataset 2 path
data = pd.read_csv(file_path)

# 1. Map "Machine failure" to "Downtime_Flag"
data = data.rename(columns={"Machine failure": "Downtime_Flag"})

# 2. Use "Air temperature [K]" as the Temperature field
data = data.rename(columns={"Air temperature [K]": "Temperature"})

# 3. Add synthetic Run_Time
data["Run_Time"] = np.random.uniform(50, 200, size=len(data))

# 4. Create "Machine_ID" from "Product ID"
data = data.rename(columns={"Product ID": "Machine_ID"})

# 5. Keep only the required columns
data = data[["Machine_ID", "Temperature", "Run_Time", "Downtime_Flag"]]

print(data.head())


# Save the modified DataFrame to a new CSV file
output_file_path = "train_dataset.csv"  # Replace with your desired file name and path
data.to_csv(output_file_path, index=False)  # index=False prevents saving the row numbers

print(f"Modified dataset saved to {output_file_path}")



  Machine_ID  Temperature    Run_Time  Downtime_Flag
0     L50096        300.6   97.916760              0
1     M20343        302.6   82.544664              0
2     L49454        299.3   86.061735              0
3     L53355        301.0   64.243253              0
4     M24050        298.0  197.636184              0
Modified dataset saved to train_dataset.csv


In [58]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline


# Load the modified CSV
file_path = "train_dataset.csv"  # Replace with your saved CSV file name
data = pd.read_csv(file_path)

# Separate features (X) and target (y)
X = data.drop("Downtime_Flag", axis=1)  # Features: Machine_ID, Temperature, Run_Time
y = data["Downtime_Flag"]               # Target: Downtime_Flag

# If "Machine_ID" is categorical, perform one-hot encoding
if "Machine_ID" in X.columns:
    X = pd.get_dummies(X, columns=["Machine_ID"], drop_first=True)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Create a pipeline with imputer to handle missing values, scaling, and Logistic Regression
clf = make_pipeline(
    SimpleImputer(strategy='mean'),  # Impute missing values with the mean
    StandardScaler(),  # Scale features for better model performance
    LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')  # Handle class imbalance
)

# Train the model
clf.fit(X_train, y_train)

# Evaluate the model
y_pred = clf.predict(X_test)

print("Logistic Regression Results:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))





KeyboardInterrupt: 

In [75]:
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load your dataset
data = pd.read_csv("manufacturing_data.csv")

# Step 2: Define features (X) and target (y)
X = data.drop(columns=["Downtime", "Machine_ID", "Date", "Assembly_Line_No"])  # Drop irrelevant fields
y = (data["Downtime"] == "Machine_Failure").astype(int)  # Convert to binary target (1 = Failure)

# Step 3: Handle missing values
# Impute missing values with the mean (for numerical data)
imputer = SimpleImputer(strategy="mean")
X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

# Step 4: Feature selection (use mutual information to select the top k features)
feature_selector = SelectKBest(score_func=mutual_info_classif, k=8)  # Choose top 8 features
X_selected = feature_selector.fit_transform(X_imputed, y)

# Step 5: Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42, stratify=y)

# Step 6: Create a pipeline for scaling and logistic regression
clf = Pipeline([
    ("scaler", StandardScaler()),  # Scale features
    ("logreg", LogisticRegression(max_iter=500, random_state=42, class_weight="balanced"))
])

# Step 7: Train the model
clf.fit(X_train, y_train)

# Step 8: Evaluate using cross-validation
cv_scores = cross_val_score(clf, X_train, y_train, cv=5, scoring="accuracy")
print("Cross-Validation Accuracy Scores:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())

# Step 9: Evaluate on the test set
y_pred = clf.predict(X_test)
print("\nTest Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Optional: Get selected feature names for analysis
selected_features = X.columns[feature_selector.get_support()]
print("\nSelected Features:", selected_features.tolist())


Cross-Validation Accuracy Scores: [0.835  0.8425 0.8725 0.86   0.84  ]
Mean CV Accuracy: 0.85

Test Accuracy: 0.878
Confusion Matrix:
 [[220  27]
 [ 34 219]]
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.89      0.88       247
           1       0.89      0.87      0.88       253

    accuracy                           0.88       500
   macro avg       0.88      0.88      0.88       500
weighted avg       0.88      0.88      0.88       500


Selected Features: ['Hydraulic_Pressure(bar)', 'Coolant_Pressure(bar)', 'Coolant_Temperature', 'Tool_Vibration(?m)', 'Spindle_Speed(RPM)', 'Torque(Nm)', 'Cutting(kN)', 'Runtime(hours)']


In [77]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.impute import SimpleImputer
import pandas as pd

# Step 1: Load the dataset
data = pd.read_csv("manufacturing_data.csv")

# Step 2: Define features (X) and target (y)
X = data.drop(columns=["Downtime", "Machine_ID", "Date", "Assembly_Line_No"])  # Drop irrelevant fields
y = (data["Downtime"] == "Machine_Failure").astype(int)  # Convert to binary target (1 = Failure)

# Step 3: Handle missing values
imputer = SimpleImputer(strategy="mean")
X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

# Step 4: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42, stratify=y)

# Step 5: Train a Random Forest Classifier
rf_clf = RandomForestClassifier(
    n_estimators=100,          # Number of trees
    max_depth=None,            # No depth limit
    random_state=42,           # For reproducibility
    class_weight="balanced"    # Handle class imbalance
)
rf_clf.fit(X_train, y_train)

# Step 6: Evaluate using cross-validation
cv_scores = cross_val_score(rf_clf, X_train, y_train, cv=5, scoring="accuracy")
print("Cross-Validation Accuracy Scores:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())

# Step 7: Evaluate on the test set
y_pred = rf_clf.predict(X_test)
print("\nTest Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Optional: Feature importance analysis
feature_importances = pd.Series(rf_clf.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nFeature Importances:\n", feature_importances)


import joblib

# Step 8: Save the trained model to a file
joblib.dump(rf_clf, 'random_forest_model.pkl')
print("Model saved to random_forest_model.pkl")



Cross-Validation Accuracy Scores: [0.9825 0.9875 0.9875 0.97   0.985 ]
Mean CV Accuracy: 0.9825000000000002

Test Accuracy: 0.988
Confusion Matrix:
 [[244   3]
 [  3 250]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       247
           1       0.99      0.99      0.99       253

    accuracy                           0.99       500
   macro avg       0.99      0.99      0.99       500
weighted avg       0.99      0.99      0.99       500


Feature Importances:
 Torque(Nm)                         0.234152
Hydraulic_Pressure(bar)            0.213442
Cutting(kN)                        0.182927
Coolant_Pressure(bar)              0.154502
Spindle_Speed(RPM)                 0.075280
Runtime(hours)                     0.059906
Coolant_Temperature                0.027212
Spindle_Bearing_Temperature(?C)    0.009835
Hydraulic_Oil_Temperature(?C)      0.009377
Spindle_Vibration(?m)              0.009345
Tool_Vibration